
services:
  tidb:
    image: pingcap/tidb:latest
    container_name: tidb
    restart: unless-stopped
    ports:
      - "4000:4000"  
      - "10080:10080" 
    command:
      - --store=unistore
      - --path=/tmp/tidb
      - -L=info
      - -initialize-insecure
    volumes:
      - tidb_data:/tmp/tidb

  aplsonic:
    image: ghcr.io/dwiftejb/aplsonic:latest
    build: .
    container_name: aplsonic
    restart: unless-stopped
    depends_on:
      - tidb
    ports:
      - "4533:4533" # subsonic api
      - "4534:4534" # admin panel
    volumes:
      - ./config/configuration.docker.yml:/app/configuration.yml:ro
      - aplsonic_data:/data # music + album-art cache

volumes:
  tidb_data:
  aplsonic_data:
