
services:
  tidb:
    image: pingcap/tidb:latest
    container_name: tidb
    restart: unless-stopped
    ports:
      - "4000:4000"  
      - "10080:10080" 
    command:
      - --store=unistore
      - --path=/tmp/tidb
      - -L=info
      - -initialize-insecure
    volumes:
      - tidb_data:/tmp/tidb
    
volumes:
  tidb_data:
  