# for aio image
database:
  host: 127.0.0.1
  port: 3306
  user: root
  password:
  database: aplsonic

port: 4533
web_port: 4534
sync_on_search: false
download: "play"

storage:
  mode: filesystem
  path: /data/storage
  download_codec: aac-web

token_check_hours: 6
token_warn_days: 7
token_auto_renew: false
